/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "Helper.h"


//==============================================================================
OnsetDetectorAudioProcessor::OnsetDetectorAudioProcessor()
{
    odValue = false;
}

OnsetDetectorAudioProcessor::~OnsetDetectorAudioProcessor()
{
}

//==============================================================================
const String OnsetDetectorAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int OnsetDetectorAudioProcessor::getNumParameters()
{
    return 0;
}

float OnsetDetectorAudioProcessor::getParameter (int index)
{
    return 0.0f;
}

void OnsetDetectorAudioProcessor::setParameter (int index, float newValue)
{
}

const String OnsetDetectorAudioProcessor::getParameterName (int index)
{
    return String();
}

const String OnsetDetectorAudioProcessor::getParameterText (int index)
{
    return String();
}

const String OnsetDetectorAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String OnsetDetectorAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool OnsetDetectorAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool OnsetDetectorAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool OnsetDetectorAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool OnsetDetectorAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool OnsetDetectorAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double OnsetDetectorAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int OnsetDetectorAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int OnsetDetectorAudioProcessor::getCurrentProgram()
{
    return 0;
}

void OnsetDetectorAudioProcessor::setCurrentProgram (int index)
{
}

const String OnsetDetectorAudioProcessor::getProgramName (int index)
{
    return String();
}

void OnsetDetectorAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void OnsetDetectorAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
    
    od.setup(samplesPerBlock);
}

void OnsetDetectorAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

std::vector<float> OnsetDetectorAudioProcessor::bufferToMonoVector(AudioSampleBuffer& buffer)
{
    std::vector<float> monoVector;
    
    const float* l = buffer.getReadPointer(0);
    const float* r = buffer.getReadPointer(0);
    
    if(buffer.getNumSamples())
    
    for(int i=0; i<buffer.getNumSamples(); i++) {
        float sample = l[i];
        
        if(buffer.getNumChannels() == 2)
            sample = Helper::f_mono(l[i], r[i]);
        
        monoVector.push_back(sample);
    }
    
    return monoVector;
}

void OnsetDetectorAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    
    std::vector<float> signal = bufferToMonoVector(buffer);
    
    odValue = od.hasOnset(signal);    

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data...
    }
}

//==============================================================================
bool OnsetDetectorAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* OnsetDetectorAudioProcessor::createEditor()
{
    return new OnsetDetectorAudioProcessorEditor (*this);
}

//==============================================================================
void OnsetDetectorAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void OnsetDetectorAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new OnsetDetectorAudioProcessor();
}
